### ISSUE TITLE
Paywall-free copy of paper?

### ISSUE THREAD

**Issue by bobobo1618** [adammj/ecg-sleep-staging#2]
Sorry if this isn't the appropriate forum but would it be possible to make the original paper available without a paywall? Perhaps a PDF copy in the repository?

**Comment by adammj** [comment]
I wish I could, but I cannot share the published article or accepted manuscript here ([Elsevier's sharing policy](https://www.elsevier.com/about/policies-and-standards/sharing)). After the 1yr embargo, I have more options for how I can share the accepted manuscript.

For now, the [preprint version](https://www.medrxiv.org/content/10.1101/2023.10.13.23297018v1) is available. Unfortunately, medRxiv doesn't allow updating the preprint with the accepted manuscript; they just allow adding a link to the published journal 😡. The most significant difference between the final and preprint versions is that the extensive meta-analysis comparison. There are, of course, numerous other minor differences. However, nothing changed about the network or the testing set results. I will look at adding the accepted manuscript to my personal homepage this weekend.

**Comment by bobobo1618** [comment]
Awesome, thanks! The preprint is plenty, I just wanted some more depth than the abstract alone offered :)

**Comment by adammj** [comment]
For future reference, I just added the preprint links to the repository and website.
