### ISSUE TITLE
Inference-only issues

### ISSUE THREAD

**Issue by bobobo1618** [adammj/ecg-sleep-staging#3]
I'm trying to run the code against an ECG recording of my own. The original data is collected using a Polar H10 chest strap using the "ECG Logger" app. I've attempted to process it to meet the requirements ([notebook](https://nbviewer.org/gist/bobobo1618/151d9d483afac5c78eda36352ffb8189)).

However I ran into a couple of issues:
- The `requirements.txt` files don't match the standard conventions `pip install -r` expects. `requirements.txt` doesn't support requiring Python version as far as I know and the package for PyTorch is just `torch`.
- I run into an `is broken` error when running `train.py`. When I make [the exception handling](https://github.com/adammj/ecg-sleep-staging/blob/47c4fe1689a9144e5178d2f0dee50c4cd07a13d9/your_own_data/primary_model/sleepdataset.py#L172-L173) more helpful, I run into `Unable to open object (object 'stages' doesn't exist)` at `stages_tensor = torch.LongTensor(file_h["stages"][()])`. I can get past that by adjusting [these lines](https://github.com/adammj/ecg-sleep-staging/blob/47c4fe1689a9144e5178d2f0dee50c4cd07a13d9/your_own_data/primary_model/sleepdataset.py#L150-L154) to read the epoch count from the `ecgs` dataset and only trying to set the `target_stages` when `stages` is present in the source file.
- Similarly, there's code [here](https://github.com/adammj/ecg-sleep-staging/blob/47c4fe1689a9144e5178d2f0dee50c4cd07a13d9/your_own_data/primary_model/sleepdataset.py#L216-L219) that tries to calculate model performance during inference, which can't be done if you don't have pre-graded data.

I managed to get through it after commenting and hacking my way through things but thought I'd let you know in case it should be cleaned up to be a bit more friendly.

**Comment by bobobo1618** [comment]
FWIW, [here's](https://nbviewer.org/gist/bobobo1618/b0d516b916c414bbc718c4044b3f289f) a notebook illustrating how I produced the input file and read the output file.

**Comment by adammj** [comment]
> The requirements.txt files don't match the standard conventions

It was created with conda. Sorry, I don't use pip for torch and other packages that have more complex requirements. Using conda, the proper way to specify PyTorch is with `pytorch`, see: [PyTorch installation](https://pytorch.org/get-started/locally/).

On the code requiring `stages`, I see that issue now. I thought I had cleaned up most of those issues for future "inference-only" cases. The final instances I will have to think a little harder about. The "problem" regardless will be that the the kappa that the code spits back will be wrong (since the stages that it predicts are not being compared against a human or other scorer). A temporary solution for now is just to create a `stages` variable of size (epochs, 1) that is all 0s. This will allow the dataloader to run.

I will get to work on removing this last instance.

**Comment by adammj** [comment]
Okay, all code trying to load the "stages" variable from an input file is now behind a conditional testing for is_training. This should fix any issues.

Again, the kappa value reported while performing inference (and the confusion matrix inside the results file) will be nonsense, as there is nothing to compare with. Which, as we know, is expected.

**Comment by adammj** [comment]
And thank you for reporting these issues. I've only ever run this code on my own machines, with the files that I generated for myself during training and development. I've been modifying the code to more useable for others somewhat blindly (in this case, I was still loading my original training data files, so I didn't catch all of the inference-only issues).

**Comment by adammj** [comment]
> FWIW, [here's](https://nbviewer.org/gist/bobobo1618/b0d516b916c414bbc718c4044b3f289f) a notebook illustrating how I produced the input file and read the output file.

On a quick inspection,  see a few issues with your ECG pre-processing code:

 - I don't see that you've high-pass filtered (0.5 Hz) the data, that is definitely required.
 - I actually would NOT recommend zeroing out "bad" epochs. The more data you can provide the better. In fact, per the paper, even if an epoch was completely junk data (unless it was a loose lead, where the signal just bounced back and forth between extremes), I would always just give it a very low weight (during training). (And I only used a weight=0 when the score provided by the expert scorer was "unknown" or "unscored")
 - Don't remove the median on an epoch by epoch basis. I just cleaned up the README a little on this point. But first you should remove the median before cutting up (reshaping) the data. And the reshaping should be the last operation.
 - Similarly, your scaling is not quite correct. The scaling should be done after removing the median and before reshaping. It should not be on an epoch-by-epoch basis. Also, your solution might work for now, but the data is not supposed to be scaled based on the min/max values of ALL data, but just on the heartbeats themselves. If your data is completely free of noise, then this will probably produce the same result. But if there are a transient bursts of noise (which is quite common), those values will often exceed the values of the heartbeats themselves, and should not be used in the scaling calculation.
     - To clarify an important piece, you want your heartbeats to fill as much of the [-0.5, 0.5] range as possible, but rarely exceed it (< 10% of the beats).
 - Make sure you add a final check to clamp all values outside [-1, 1]. (The loader will now check for this and throw an error).

(On this note, sorry, I am still working occasionally to convert my full MATLAB pipeline to Python. There's just a lot of code.)

**Comment by bobobo1618** [comment]
Thanks! I can confirm that after pulling your changes everything works great.

Regarding my pre-processing, thanks for the feedback! I have little idea what I'm doing so much appreciated.

> I don't see that you've high-pass filtered (0.5 Hz) the data, that is definitely required.

It's handled by Neurokit's [`ecg_process`](https://neuropsychology.github.io/NeuroKit/functions/ecg.html#ecg-process), which applies a 0.5Hz order 5 Butterworth high-pass filter and a 50Hz filter for powerline noise.

> I actually would NOT recommend zeroing out "bad" epochs. 

I did that because I remembered reading "silencing" in the back of my mind while I was writing the code and thought that with a consumer ECG wearable, more filtering might be needed. I never bothered to actually check.

Having removed that filtering, the result subjectively looks much better so it seems like it was misplaced.

> Don't remove the median on an epoch by epoch basis. I just cleaned up the README a little on this point. But first you should remove the median before cutting up (reshaping) the data. And the reshaping should be the last operation.

Another thing I did without really thinking. For some reason I thought there was still long-term baseline wander left after filtering and thought it'd be a good idea to do this to reduce it. Removed this and the result looks better.

> Similarly, your scaling is not quite correct.

This is the part where my lack of mathematical ability was hurting the most.

Best I've come up with now is finding the 90th percentile value for the R-peaks and multiplying the signal by a scalar such that the 90th percentile becomes 0.5.

[Updated notebook if you're interested](https://nbviewer.org/gist/bobobo1618/6492bc988d427db83a463801ecc5848f).

**Comment by adammj** [comment]
I'm glad to hear it's working!

**Comment by adammj** [comment]
@bobobo1618 One additional thing you could do to make the heartbeat scaling a little more robust is to get the max(abs(values around R wave)) (say for +/- 0.3 sec). The possible problem with assuming that the R wave will always be the tallest peak, is that... it isn't always the tallest peak. Sometimes the T wave will be taller, and occasionally the Q or S (although negative polarity) can be further from the baseline.

The algorithm I use is more robust than this. But this slight tweak will get you most of the way there to robustly handling perfectly normal data.

**Comment by bobobo1618** [comment]
Thanks, [done](https://nbviewer.org/gist/bobobo1618/c98a685c1b2069df9d00c008a893ffa9)!

I'm curious whether the model is able to handle consumer chest band ECG recordings though. I recorded this ECG with a Movesense device and the waveform looks rather odd:
![bokeh_plot-3](https://github.com/user-attachments/assets/7ced83aa-9d9d-4bfd-98dc-3ae4361dfd39)

Capture with a Polar H10 looks a bit more reasonable:
![bokeh_plot-4](https://github.com/user-attachments/assets/8cb8950c-5913-4666-85e8-ca0b433038e5)

I intend to check by recording with both a chest band and something closer to a proper ECG Lead I and comparing the results but curious if you have any insights.

**Comment by adammj** [comment]
When I started the precursor to this research, I was under the assumption that all ECG data (baring any environmental noise) looked just liked the textbook examples. It does not. Not even close.

I have over 250,000 hours of clinical ECG data at my disposal, and the amount of natural variation, hour to hour in the same recording, day to day in the same subject (although "day to day" could be separated by months or years), or subject to subject at the same recording site, is just bonkers. Some of that is obviously to do with how well the sleep technicians actually hooked up the equipment. They might've placed the leads in slightly different places, or even reversed the connections. And some is the variations in the subject. The heart isn't the same size or shape, nor is not perfectly oriented in the same way in every chest. They could have had or will soon have a heart attack, some arrhythmia due to disease, or on some medication or diet that affects the ion concentrations and therefore the electrical conduction as the action potentials are traveling across the heart. I trained my network on it all, because I wanted to make the network as robust to all of those variations as possible.

With all that said, your median heartbeats easily fall within the normal variation that the network was trained on.

**Comment by bobobo1618** [comment]
Thanks for the extra context! My concern was mostly variation in recordings for a single subject (myself).

As a very basic sanity check of my processing and setup, I compared the results of a Polar H10 run through your model to results from a Muse S headband (EEG-based) and the REM periods at least line up quite well. Muse shows less "deep" sleep but in my experience it wasn't overly precise in comparison to the Dreem headband (which has clinical validation), so I'm fairly confident it's Muse making the mistake here rather than your model.

Also if you're interested, I updated [my notebook](https://nbviewer.org/gist/bobobo1618/a9c4ab2eca3fe4207d80ca85c519b904) to interface with the model directly rather than using `train.py`. Even managed to [port it to Google Colab](https://colab.research.google.com/drive/1_NN14fnkApZBk32osn5BcE97_FsrWG3T?usp=sharing), complete with Python dependency installation. Neurokit's `ecg_process` ran out of RAM though so didn't actually get to execute it...

You addressed the actual issues I was having ages ago so I'll close the bug now. Thanks again for all the help!

**Comment by adammj** [comment]
@bobobo1618 Wow, you've got (at least) a Polar H10, Movesense, Muse S, and Dreem. I'm curious if you mind me asking what it is you do, or are you just a very interested hobbyist? Feel free to respond by email, if you like (mine is listed on the published paper's website, if you click my name).

**Comment by adammj** [comment]
@bobobo1618 If you tried emailing me yesterday, I think my app ate the email. I saw something come in my spam folder that mentioned git or repo, but when I went to read it 30 minutes later, it was gone. And unfortunately I can't seem to find any trace of it on the server or locally. If it wasn't you, feel free to ignore. (If it was someone else, I'll just have to hope they email me again.)

**Comment by bobobo1618** [comment]
Yep, it was me. Forwarded the original email to you again, hopefully it gets through this time!
